name: Deploy

on:
  push:
    branches:
      - main
      - deploy
    paths:
      - package.json
      - yarn.lock
      - next.config.js
      - .github/**
      - public/**
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🔑 Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare env
        run: |
          cat <<EOT >> .env

          DB_NAME=${{ secrets.DB_NAME }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          NEXT_PUBLIC_SOCKET_URL=https://messages.fictionaldev.com
          NEXT_PUBLIC_AUTH_CLIENT_ID=9b0a29ac737d605e50a1ecae49e1a1e8753bf738709042901458efba3874e95c
          SHARE_TOKEN_SECRET=${{ secrets.SHARE_TOKEN_SECRET }}
          NEXT_PUBLIC_AUTH_BASE_URL=https://auth.fictionaldev.com
          NEXT_PUBLIC_AUDIENCE=https://salt.fictionaldev.com
          
          S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}

          EOT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 🐳 Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dmitryhoncharuk/salt
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - run: doctl kubernetes cluster kubeconfig save ficdev

      - name: Create namespace
        run: kubectl create namespace salt || true

      - name: Create configmap
        run: |
          kubectl -n=salt delete configmap salt-env-config || true
          kubectl -n=salt create configmap salt-env-config --from-env-file=.env

      - run: kubectl -n=salt rollout restart deployment salt-deployment

      - name: 🚚 Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
